config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users
  resources :login

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= session[:current_user_id] &&
    User.find_by(id: session[:current_user_id])
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user = User.find_by(:email => params[:user][:email]).try(:authenticate, params[:user][:password])
      session[:current_user_id] = user.id
      redirect_to root_url
    else
      @user = User.new
      flash.now[:error] = 'Email / password is invalid'
      render :new
    end
  end

  def destroy
    @_current_user = session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_parameters)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def allowed_parameters
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.find_by(id: session[:current_user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>
<%= yield %>

</body>
</html>

app/views/login/new.html.erb
<%= form_for @user, {url: '/login', :method => 'post'} do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit 'Log in' %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Sign up' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the lending library
  <% if @user %>
    <%= @user.email %></h1>
    <%= link_to 'Log out', login_path(@user), :method => :delete %>
  <% else %>
    </h1>
    <%= link_to 'Log in', new_login_path %>
    <%= link_to 'Sign up', new_user_path %>
  <% end %>